%% 125 Hz transposed stimuli in and out of phase
InterauralTonePhase=pi;
ToneFreq=125;
TranspositionFreq = 4000;
NoiseBandWidth=100;
BackNzLevel=0.01;

NumSignalPulses= 3;
ToneDuration=250;
WithinPulseISI=30;
ISI=300;
signalInterval = NumSignalPulses*ToneDuration + (NumSignalPulses-1) * WithinPulseISI;
NoiseDuration=signalInterval;
LongMaskerNoise= 600 + 3 * NoiseDuration + 2 * ISI;

Berniotis('SR','fixed','noise','rms2use', 0.07,'NoiseBandWidth',NoiseBandWidth,...
    'InterauralTonePhase', InterauralTonePhase, 'TranspositionFreq', TranspositionFreq,'ToneFreq', ToneFreq, ...
    'VolumeSettingsFile', 'VolumeSettings4kHz.txt', ...
    'NumSignalPulses', NumSignalPulses,'ToneDuration', ToneDuration, 'WithinPulseISI', WithinPulseISI,...
    'NoiseDuration', NoiseDuration,'ISI', ISI, ...
    'starting_SNR',12,...
    'BackNzPulsed', 0, 'BackNzLoPass', 1300, 'BackNzHiPass', 50, 'BackNzLevel', BackNzLevel, ...
    'LongMaskerNoise', LongMaskerNoise, ...
    'PlotTrackFile', 1, 'outputAllWavs', 1, 'DEBUG',1);
return
InterauralTonePhase=pi;
Berniotis('SR','fixed','noise','rms2use', 0.07,'NoiseBandWidth',NoiseBandWidth,...
    'InterauralTonePhase', InterauralTonePhase, 'TranspositionFreq', TranspositionFreq,'ToneFreq', ToneFreq, ...
    'VolumeSettingsFile', 'VolumeSettings4kHz.txt', ...
    'NumSignalPulses', NumSignalPulses,'ToneDuration', ToneDuration, 'WithinPulseISI', WithinPulseISI,...
    'NoiseDuration', NoiseDuration,'ISI', ISI, ...
    'starting_SNR',10,...
    'BackNzPulsed', 0, 'BackNzLoPass', 1300, 'BackNzHiPass', 50, 'BackNzLevel', BackNzLevel, ...
    'LongMaskerNoise', LongMaskerNoise, ...
    'PlotTrackFile', 1, 'outputAllWavs', 1, 'DEBUG',0);
return

%% 500 Hz tonal stimuli in and out of phase: No background noise
InterauralTonePhase=0;
ToneFreq=500;
TranspositionFreq = 000;

NoiseBandWidth=900;
NumSignalPulses= 3;
ToneDuration=200;
WithinPulseISI=30;
ISI=300;
signalInterval = NumSignalPulses*ToneDuration + (NumSignalPulses-1) * WithinPulseISI;
NoiseDuration=signalInterval;
LongMaskerNoise= 600 + 3 * NoiseDuration + 2 * ISI;
BackNzLevel=0;
Berniotis('SR','fixed','noise','rms2use', 0.07,'NoiseBandWidth',NoiseBandWidth,...
    'InterauralTonePhase', InterauralTonePhase, 'TranspositionFreq', TranspositionFreq,'ToneFreq', ToneFreq, ...
    'VolumeSettingsFile', 'VolumeSettings4kHz.txt', ...
    'NumSignalPulses', NumSignalPulses,'ToneDuration', ToneDuration, 'WithinPulseISI', WithinPulseISI,...
    'NoiseDuration', NoiseDuration,'ISI', ISI, ...
    'starting_SNR',10,...
    'BackNzPulsed', 0, 'BackNzLoPass', 1300, 'BackNzHiPass', 50, 'BackNzLevel', BackNzLevel, ...
    'LongMaskerNoise', LongMaskerNoise, ...
    'PlotTrackFile', 1, 'outputAllWavs', 1, 'DEBUG',0);
InterauralTonePhase=pi;
Berniotis('SR','fixed','noise','rms2use', 0.07,'NoiseBandWidth',NoiseBandWidth,...
    'InterauralTonePhase', InterauralTonePhase, 'TranspositionFreq', TranspositionFreq,'ToneFreq', ToneFreq, ...
    'VolumeSettingsFile', 'VolumeSettings4kHz.txt', ...
    'NumSignalPulses', NumSignalPulses,'ToneDuration', ToneDuration, 'WithinPulseISI', WithinPulseISI,...
    'NoiseDuration', NoiseDuration,'ISI', ISI, ...
    'starting_SNR',10,...
    'BackNzPulsed', 0, 'BackNzLoPass', 1300, 'BackNzHiPass', 50, 'BackNzLevel', BackNzLevel, ...
    'LongMaskerNoise', LongMaskerNoise, ...
    'PlotTrackFile', 1, 'outputAllWavs', 1, 'DEBUG',0);
return

